apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: Authorization__URL
              value: http://authorization-api:8005/validate
            - name: RabbitMQConnection__Host
              value: rabbitmq
            - name: RabbitMQConnection__Password
              value: AbstractTasks
            - name: RabbitMQConnection__Username
              value: AbstractTasks
          image: api
          imagePullPolicy: Never
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
