// <auto-generated />
using System;
using AbstractTasksDal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations.Stock
{
    [DbContext(typeof(StockContext))]
    [Migration("20251007214011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Entities.StockEntity", b =>
                {
                    b.Property<Guid>("IDStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "IDStock");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "Address");

                    b.Property<bool>("CardPayment")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "CardPayment");

                    b.Property<bool>("CashPayment")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "CashPayment");

                    b.Property<string>("ConsigneeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ConsigneeCode");

                    b.Property<Guid>("FIASId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "FIASId");

                    b.Property<Guid>("IDDivision")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "IDDivision");

                    b.Property<string>("OwnerFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OwnerFullName");

                    b.Property<string>("OwnerInn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OwnerInn");

                    b.Property<string>("OwnerKpp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OwnerKpp");

                    b.Property<string>("OwnerShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OwnerShortName");

                    b.Property<string>("RailwayStation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "RailwayStation");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "Schedule");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "Stock");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "StockName");

                    b.HasKey("IDStock");

                    b.ToTable("_stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
